title: Matt Ashall # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior Data Scientist with previous Operations Management experience.
  <br><br>
  Looking for a role to develop as a data scientist, and get stuck in to using data to facilitate better decision making by business managers, and improve business processes. 
  <br><br>
  <a href="https://www.linkedin.com/in/matthew-ashall/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
